# Generated by Django 4.2.14 on 2025-02-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('language_options', models.IntegerField(default=0, help_text='Количество языков, которые можно выбрать')),
                ('starting_equipment', models.TextField(blank=True, null=True)),
                ('feature_name', models.CharField(blank=True, max_length=100, null=True)),
                ('feature_description', models.TextField(blank=True, null=True)),
                ('skill_proficiencies', models.ManyToManyField(blank=True, related_name='backgrounds_with_proficiency', to='main.proficiency')),
            ],
        ),
    ]
