# Generated by Django 4.2.14 on 2025-02-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='skill_proficiencies',
            field=models.ManyToManyField(blank=True, related_name='backgrounds_with_proficiency', to='main.skill'),
        ),
    ]
