# Generated by Django 4.2.14 on 2025-02-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_background_skill_proficiencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='tool_proficiencies',
            field=models.ManyToManyField(blank=True, related_name='backgrounds_with_proficiency', to='main.proficiency'),
        ),
        migrations.AlterField(
            model_name='background',
            name='skill_proficiencies',
            field=models.ManyToManyField(blank=True, related_name='backgrounds_with_skills', to='main.skill'),
        ),
    ]
